# Generated by Django 4.2.7 on 2026-03-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, help_text='EAN / UPC barcode', max_length=50, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('brand', models.CharField(blank=True, default='', max_length=255)),
                ('image_url', models.URLField(blank=True, default='', max_length=2000)),
                ('ingredients_text', models.TextField(blank=True, default='', help_text='Full English ingredient list')),
                ('categories', models.TextField(blank=True, default='', help_text="Comma-separated categories, e.g. 'Noodles, Instant Food'")),
                ('nutriments', models.JSONField(blank=True, help_text='Nutrition rows — list of {label, value, unit} dicts', null=True)),
                ('nutriments_raw', models.JSONField(blank=True, help_text='Raw nutriments dict from OpenFoodFacts for re-processing', null=True)),
                ('nova_group', models.IntegerField(blank=True, help_text='NOVA food processing group (1–4)', null=True)),
                ('nutriscore_grade', models.CharField(blank=True, default='', help_text='Nutri-Score grade (a/b/c/d/e)', max_length=1)),
                ('serving_size', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.CharField(blank=True, default='', help_text="Package size, e.g. '200g'", max_length=100)),
                ('country', models.CharField(blank=True, default='', help_text='e.g. India, USA', max_length=100)),
                ('is_indian', models.BooleanField(default=True, help_text='True for Indian brands — shown first in results')),
                ('is_verified', models.BooleanField(default=False, help_text='Manually confirmed — data is 100% correct')),
                ('source', models.CharField(default='OFF', help_text='Data origin: OFF (OpenFoodFacts import), Manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-is_verified', '-is_indian', 'name'],
                'indexes': [models.Index(fields=['name'], name='analyzer_pr_name_b0f7f0_idx'), models.Index(fields=['brand'], name='analyzer_pr_brand_5f9532_idx'), models.Index(fields=['is_indian', 'is_verified'], name='analyzer_pr_is_indi_17cd50_idx')],
            },
        ),
    ]
