# Generated by Django 4.2.7 on 2026-03-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url_full',
            field=models.URLField(blank=True, default='', help_text='High-resolution image', max_length=2000),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Thumbnail/Small image', max_length=2000),
        ),
    ]
